### ISSUE TITLE
DLC doesn't work in the online version

### ISSUE THREAD

**Issue by Xendergo** [treeform/istrolid-bugs#55]
When I use the online version, it runs as if I never bought the DLC

**Comment by astral-carrier** [comment]
DLC is tied to your Steam account (because it's bought through Steam), not your Istrolid account, therefore it only works when you're playing Istrolid on Steam. I guess the devs could make it so that you can also buy DLC for your Istrolid account instead of Steam, but you'll have to ask the devs about that.

**Comment by Xendergo** [comment]
I know that, but that's what I'm trying to do through this bug report (Ask the devs if they can do anything about this)

**Comment by Xendergo** [comment]
I've found a hack to give myself the DLC, I'll only use it for the paint job, because I already bought it.

**Comment by Xendergo** [comment]
I think it should still work without hacks though
